import { useEffect, useRef, useState } from 'react'
import { PublicKey } from '@solana/web3.js'
import { ArrowLeft, ArrowRight, ArrowUpRight, Check, Github, ImagePlus, Search, ShieldCheck } from 'lucide-react'
import { Keypair, addMintSignature, api, b64, checkWalletTransaction, POLICY_VERSION, prepareWalletTransaction, readRecovery, Review, storeRecovery, walletMessageMatches, type Plan } from '../packages/pump-core/client'
import { COMMIT_FEE_RECIPIENT, COMMIT_POLICY, COMMIT_CREATOR_FEE_BPS, COMMIT_MAIN_POLICY, COMMIT_MAIN_WALLET, MICROSOFT_ASSET, SOL_MINT, type CommitLaunchPolicy } from '../lib/pump/policy'
import { categories, type Category, type Development, type Project, type Repository } from '../lib/types'
import { useApp } from './context'
import { errorText, request } from './api'
import { Notice, RepoPreview } from './components'

export function Create() {
  const app = useApp(), [step, setStep] = useState(0), [repositories, setRepositories] = useState<Repository[]>([]), [next, setNext] = useState<number | null>(1), [query, setQuery] = useState('')
  const [repo, setRepo] = useState<Repository | null>(null), [development, setDevelopment] = useState<Development | null>(null), [maintainer, setMaintainer] = useState(true), [lookup, setLookup] = useState(''), [agreed, setAgreed] = useState(false), [mainCoin, setMainCoin] = useState(false), [mainExists, setMainExists] = useState(true)
  const [name, setName] = useState(''), [symbol, setSymbol] = useState(''), [description, setDescription] = useState(''), [website, setWebsite] = useState(''), [category, setCategory] = useState<Category>('Open Source')
  const treasury = COMMIT_FEE_RECIPIENT
  const [maintainers, setMaintainers] = useState(''), [buy, setBuy] = useState(''), [image, setImage] = useState<{ base64: string; type: string; preview: string } | null>(null)
  const [policy, setPolicy] = useState<CommitLaunchPolicy | null>(null), [policyError, setPolicyError] = useState('')
  const [plan, setPlan] = useState<Plan | null>(null), [busy, setBusy] = useState(''), [error, setError] = useState(''), [now, setNow] = useState(Date.now())
  const mint = useRef<Keypair | null>(null), approval = useRef<Uint8Array | null>(null), lock = useRef(false), owner = useRef(app.wallet.account?.address)
  owner.current = app.wallet.account?.address
  useEffect(() => { if (app.user) void loadRepos(1) }, [app.user?.id])
  useEffect(() => { void loadPolicy() }, [])
  useEffect(() => { void request<{ items: Project[] }>('/api/commit/projects').then(v => setMainExists(v.items.some(p => p.main))).catch(() => setMainExists(true)) }, [])
  // Commit's main coin: only for the operator, signing with the main wallet, and only while none exists.
  const mainEligible = app.payoutAdmin && app.wallet.account?.address === COMMIT_MAIN_WALLET && !mainExists
  useEffect(() => { if (!mainEligible) setMainCoin(false) }, [mainEligible])
  async function loadPolicy() { setPolicyError(''); try { const value = await request<CommitLaunchPolicy>('/api/commit/launch-policy'); if (value.version !== COMMIT_POLICY || value.quote.mint !== MICROSOFT_ASSET.mint || value.creatorFeeBps !== COMMIT_CREATOR_FEE_BPS || value.feeRecipient !== treasury) throw Error('Launch policy changed. Refresh Commit.'); setPolicy(value) } catch (e) { setPolicy(null); setPolicyError(errorText(e)) } }
  useEffect(() => { const timer = setInterval(() => setNow(Date.now()), 1000); return () => clearInterval(timer) }, [])
  useEffect(() => { if (plan && plan.owner !== app.wallet.account?.address) { setPlan(null); mint.current = null; approval.current = null; setError('Wallet changed. Review the launch again.') } }, [app.wallet.account?.address, plan])
  async function loadRepos(page: number) { setBusy('Loading authorized repositories…'); setError(''); try { const data = await request<{ items: Repository[]; next: number | null }>(`/api/commit/repositories?page=${page}`); setRepositories(old => page === 1 ? data.items : [...new Map([...old, ...data.items].map(r => [r.id, r])).values()]); setNext(data.next) } catch (e) { setError(errorText(e)) } finally { setBusy('') } }
  async function choose(ref: { id: number } | { repository: string }) { setBusy('Checking the repository with GitHub…'); setError(''); try { const data = await request<{ repo: Repository; maintainer: boolean; development: Development }>('/api/commit/repositories/verify', ref); setRepo(data.repo); setMaintainer(data.maintainer); setAgreed(false); setDevelopment(data.development); setName(data.repo.name.slice(0, 32)); setDescription(data.repo.description); setStep(1) } catch (e) { setError(errorText(e)) } finally { setBusy('') } }
  async function upload(file?: File) { setError(''); setImage(null); if (!file) return; if (!['image/png', 'image/jpeg', 'image/gif', 'image/webp'].includes(file.type) || file.size > 5 * 1024 * 1024) { setError('Choose a PNG, JPEG, GIF or WebP image up to 5 MB.'); return } const base64 = b64(new Uint8Array(await file.arrayBuffer())); setImage({ base64, type: file.type, preview: `data:${file.type};base64,${base64}` }) }
  function advance() {
    setError('')
    try {
      if (step === 1) {
        if (!name.trim() || new TextEncoder().encode(name.trim()).length > 32 || !symbol.trim() || new TextEncoder().encode(symbol.trim()).length > 10 || new TextEncoder().encode(description).length > 1000 || !image) throw Error('Choose an image, a name up to 32 UTF-8 bytes, a ticker up to 10 bytes, and a description up to 1,000 bytes.')
        if (website && new URL(website).protocol !== 'https:') throw Error('Website must use HTTPS.')
      }
      if (step === 2) maintainers.split(/[\s,]+/).filter(Boolean).forEach(v => new PublicKey(v))
      if (step === 3 && !app.wallet.account) { app.connect(); return }
      setStep(step + 1)
    } catch (e) { setError(errorText(e)) }
  }
  async function prepare() {
    if (lock.current || !repo || !image || !app.wallet.account || app.pending || readRecovery()) return
    if (!policy && !mainCoin) { setError('Wait for verification of the Microsoft / 2% launch policy.'); return }
    lock.current = true; setError(''); setBusy('Publishing metadata and simulating with Pawns…'); approval.current = null
    const account = app.wallet.account.address
    try {
      const main = mainCoin && mainEligible, recipient = main ? COMMIT_MAIN_WALLET : treasury
      const metadata = await api<{ hash: string }>('metadata', { repositoryId: repo.id, name, symbol, description, website, twitter: '', telegram: '', image: image.base64, imageType: image.type, ...(main ? { commitPolicy: COMMIT_MAIN_POLICY } : {}) })
      const signer = Keypair.generate()
      const result = await api<Plan>('prepare', { repositoryId: repo.id, treasury: recipient, category, maintainerWallets: maintainers.split(/[\s,]+/).filter(Boolean), owner: account, mint: signer.publicKey.toBase58(), metadata: metadata.hash, buy: buy || '0', quoteMint: main ? SOL_MINT : MICROSOFT_ASSET.mint, creatorTax: main ? '0' : '2', policyVersion: POLICY_VERSION, commitPolicy: main ? COMMIT_MAIN_POLICY : COMMIT_POLICY })
      if (owner.current !== account) throw Error('Wallet changed during preparation. Review again.')
      const pairOk = main ? result.quote?.mint === SOL_MINT && result.quote.decimals === 9 && result.creatorTaxBps === 0 : result.quote?.mint === MICROSOFT_ASSET.mint && result.quote.decimals === 8 && result.creatorTaxBps === COMMIT_CREATOR_FEE_BPS
      if (result.feeRecipient !== recipient || !pairOk || result.policyVersion !== POLICY_VERSION || result.owner !== account || result.mint !== signer.publicKey.toBase58()) throw Error('Prepared launch does not match the Microsoft pair, 2% fee, collector, and wallet.')
      mint.current = signer; setPlan(result)
    } catch (e) { setError(errorText(e)) } finally { lock.current = false; setBusy('') }
  }
  async function confirm() {
    if (lock.current || !plan || !mint.current || app.pending) return
    if (!navigator.locks) { setError('Use a current browser with Web Locks support to coordinate transaction signing.'); return }
    const initial = plan, signer = mint.current
    await navigator.locks.request(`pawn-solana-launch-${plan.owner}`, { ifAvailable: true }, async held => {
      if (!held || readRecovery()) { setError('Another transaction is active. Resolve it before continuing.'); return }
      lock.current = true; setBusy('Confirm in your Solana wallet…'); setError('')
      let reviewed = initial
      try {
        if (Date.now() >= reviewed.expiresAt) throw Error('Review expired. Prepare a fresh review.')
        const signed = approval.current || await app.wallet.sign(prepareWalletTransaction(reviewed, signer), reviewed.owner)
        if (!walletMessageMatches(signed, reviewed)) {
          const accepted = await api<{ plan: Plan; requiresFeeApproval: boolean }>('wallet-review', { id: reviewed.id, transaction: b64(signed) })
          reviewed = accepted.plan; checkWalletTransaction(signed, reviewed)
          if (owner.current !== reviewed.owner) throw Error('Wallet changed. Review again.')
          if (accepted.requiresFeeApproval) { approval.current = signed; setPlan(reviewed); setError('Your wallet adjusted the network fee. Review the updated amount, then confirm the already-signed transaction.'); return }
        }
        if (owner.current !== reviewed.owner) throw Error('Wallet changed. Review again.')
        const bytes = addMintSignature(signed, reviewed, signer), signature = checkWalletTransaction(bytes, reviewed)
        const record = { id: reviewed.id, owner: reviewed.owner, mint: reviewed.mint, signature, signed: b64(bytes), networkFeeLamports: reviewed.networkFeeLamports }
        storeRecovery(record); app.onPending(record, { ...reviewed, signature, status: 'pending' }); mint.current = null; approval.current = null; setPlan(null)
        setBusy('Submitting the signed Pawns transaction…')
        app.onActivity(await api<Plan>('submit', { id: record.id, transaction: record.signed, networkFeeLamports: record.networkFeeLamports }))
      } catch (e) { setError(errorText(e)) } finally { lock.current = false; setBusy('') }
    }).catch(e => setError(errorText(e)))
  }
  const steps = ['Repository', 'Token setup', 'Project treasury', 'Solana wallet', 'Review & launch']
  return <section className="container create-page"><div className="page-heading"><div className="eyebrow"><span className="section-index">CREATE /</span> YOUR NEXT CHAPTER</div><h1>Launch a repository.</h1><p>Yours or anyone’s. Any public GitHub repository can have a coin, and its maintainers claim the creator fees.</p></div><div className="create-layout"><div><ol className="wizard-steps">{steps.map((label, index) => <li key={label} className={index === step ? 'active' : index < step ? 'done' : ''}><button disabled={!!busy || !!plan || !!app.pending || index > step} onClick={() => setStep(index)} aria-current={index === step ? 'step' : undefined}><span>{index < step ? <Check size={12}/> : `0${index + 1}`}</span><span>{label}</span></button></li>)}</ol><div className="form-panel"><div className="form-panel-heading"><div className="eyebrow">STEP 0{step + 1} / 05</div><span className="mono">{step === 0 ? 'CONNECT THE SOURCE' : step === 4 ? 'READY FOR REVIEW' : 'PROJECT CONFIGURATION'}</span></div><h2>{steps[step]}</h2>{error && !plan && <p className="error" role="alert">{error}</p>}{busy && <Notice>{busy}</Notice>}
      {!app.sessionLoaded ? <Notice>Checking your GitHub session…</Notice> : !app.user ? <div className="sign-in-panel"><span className="signin-github-icon"><Github size={33}/></span><h3>It starts with GitHub.</h3><p>Sign in to launch any public repository: your own, or one you want to back. Your GitHub username is shown as the launcher.</p><a href="/api/auth/login?next=/create" className="button dark"><Github size={16}/>Continue with GitHub<ArrowUpRight size={16}/></a><span className="signin-permission"><ShieldCheck size={13}/>Creator fees go to the repository’s maintainers</span>{!app.githubConfigured && <Notice>GitHub OAuth credentials must be configured on this deployment before sign-in is available.</Notice>}</div> : <>
      <fieldset disabled={!!busy || !!plan || !!app.pending}>
        {step === 0 && <><p className="muted">Enter any public GitHub repository. If you don’t maintain it, it becomes a <b>community launch</b>: the coin shows you as the launcher, and only the repository’s maintainers (and contributors they approve) can claim its creator fees.</p><form className="repo-lookup" onSubmit={e => { e.preventDefault(); if (lookup.trim()) void choose({ repository: lookup.trim() }) }}><label className="search"><Github size={16}/><input placeholder="owner/name or github.com/owner/name" aria-label="Any public GitHub repository" value={lookup} onChange={e => setLookup(e.target.value)}/></label><button type="submit" className="button dark" disabled={!lookup.trim()}>Use repository<ArrowRight size={14}/></button></form><div className="eyebrow repo-list-label">or pick one you maintain</div><label className="search"><Search size={16}/><input placeholder="Filter your repositories" aria-label="Find your repository" value={query} onChange={e => setQuery(e.target.value)}/></label><div className="repo-options">{repositories.filter(r => `${r.owner}/${r.name}`.toLowerCase().includes(query.toLowerCase())).map(r => <button key={r.id} onClick={() => void choose({ id: r.id })}><Github size={18}/><span><strong>{r.owner} / {r.name}</strong><small>{r.language || 'Open source'} · {r.stars} stars</small></span><ArrowRight size={16}/></button>)}</div>{!repositories.length && !busy && <Notice>No repositories you maintain were found. You can still launch any public repository above. For organization repositories, check the organization’s third-party OAuth access policy.</Notice>}{next && <button className="button secondary" onClick={() => void loadRepos(next)}>{repositories.length ? 'Load more repositories' : 'Refresh repositories'}</button>}</>}
        {step === 1 && <>{!maintainer && repo && <Notice><b>Community launch.</b> You don’t maintain {repo.owner}/{repo.name}. The coin will say it was launched by @{app.user.login}, not by its maintainers, and its creator fees can only be claimed by the repository’s maintainers and the contributors they approve.</Notice>}<label className="image-input">{image ? <img src={image.preview} alt="Token image preview"/> : <ImagePlus size={28}/>}<span><strong>{image ? 'Replace token image' : 'Upload image / logo'}</strong><small>PNG, JPG, WebP or GIF · up to 5 MB</small></span><input type="file" accept="image/png,image/jpeg,image/webp,image/gif" onChange={e => void upload(e.target.files?.[0])}/></label><div className="form-row"><label>Token name<input value={name} onChange={e => setName(e.target.value)} placeholder="Your project" maxLength={32}/></label><label>Ticker<input value={symbol} onChange={e => setSymbol(e.target.value.toUpperCase())} placeholder="CODE" maxLength={10}/></label></div><label>Description<textarea value={description} onChange={e => setDescription(e.target.value)} rows={4} maxLength={1000} placeholder="What are you building?"/></label><label>Project website <span className="muted">(optional)</span><input type="url" placeholder="https://your-project.dev" value={website} onChange={e => setWebsite(e.target.value)}/></label><label>Category<select value={category} onChange={e => setCategory(e.target.value as Category)}>{categories.map(c => <option key={c}>{c}</option>)}</select></label><div className="attached-repo"><Github size={14}/>{repo?.url}<span>Automatically attached</span></div></>}
        {step === 2 && <><dl className="review-summary"><div><dt>Paired asset · locked</dt><dd>Microsoft xStock (MSFTx)</dd></div><div><dt>Creator fee · locked</dt><dd>2% · protocol fees are separate</dd></div></dl><label>Microsoft paired-asset mint<input className="mono" value={MICROSOFT_ASSET.mint} readOnly/></label><Notice>Each coin gets its own treasury ledger on Commit. Creator fees accrue in Pump.fun’s vault for Commit’s collection wallet; the signing review shows the exact recipient before you sign. Eligible GitHub users link a verified payout wallet and request a claim; Commit reviews it and manually sends MSFTx. The request button never transfers funds automatically.</Notice><label>Maintainer wallets <span className="muted">(optional project records)</span><textarea rows={3} className="mono" value={maintainers} onChange={e => setMaintainers(e.target.value)} placeholder="One Solana public address per line"/></label></>}
        {step === 3 && <><div className="wallet-step"><ShieldCheck size={34}/><h3>{app.wallet.account ? 'Your signing wallet is connected.' : 'Connect your Solana wallet.'}</h3>{app.wallet.account && <code>{app.wallet.account.address}</code>}<p>Pawns prepares and simulates the transaction. Your wallet signs it. The mint key is generated in this browser and never stored.</p><button className="button dark" onClick={app.connect}>{app.wallet.account ? 'Manage wallet' : 'Connect Solana wallet'}<ArrowUpRight size={16}/></button></div>{mainEligible && <label className="agree main-coin-option"><input type="checkbox" checked={mainCoin} onChange={e => setMainCoin(e.target.checked)}/><span><b>Launch as Commit’s main coin.</b> The one exception to the Microsoft pair: a standard SOL-paired Pump.fun coin whose creator fees go to this wallet, pinned site-wide as the main coin.</span></label>}<label>Optional opening buy · {mainCoin ? 'SOL' : 'MSFTx'}<input value={buy} onChange={e => setBuy(e.target.value)} inputMode="decimal" placeholder="0.00"/></label><p className="small muted">{mainCoin ? 'Opening buys spend SOL, plus network fees and rent.' : 'Opening buys spend Microsoft xStock, not SOL. SOL is still required for network fees and rent.'} Leave blank to launch without buying.</p></>}
        {step === 4 && !plan && <><dl className="review-summary"><div><dt>Repository</dt><dd>{repo?.owner}/{repo?.name}</dd></div><div><dt>Launch type</dt><dd>{mainCoin ? 'Commit main coin · pinned' : maintainer ? 'Maintainer launch' : `Community launch by @${app.user.login}`}</dd></div><div><dt>Token</dt><dd>{name} · ${symbol}</dd></div><div><dt>Network / pair</dt><dd>{mainCoin ? 'Solana mainnet / SOL (standard Pump.fun)' : 'Solana mainnet / Microsoft xStock (MSFTx)'}</dd></div><div><dt>Creator fee</dt><dd>{mainCoin ? 'Pump.fun standard, to the main wallet' : '2% of trades'}</dd></div>{repo?.forked && <div><dt>Fork of</dt><dd>{repo.parent ? `${repo.parent.owner}/${repo.parent.name}` : 'another repository'}</dd></div>}<div><dt>Opening buy</dt><dd>{buy || '0'} {mainCoin ? 'SOL' : 'MSFTx'}</dd></div><div><dt>Fee claims</dt><dd>{mainCoin ? 'Claimed by the main wallet on Pump.fun' : `${repo?.owner}/${repo?.name} maintainers + approved contributors`}</dd></div><div><dt>Project payouts</dt><dd>{mainCoin ? 'Direct: no Commit payout requests' : 'Requested on Commit; sent manually'}</dd></div></dl>{mainCoin ? null : policyError ? <Notice>{policyError} <button className="inline-button" onClick={() => void loadPolicy()}>Retry policy check</button></Notice> : !policy && <Notice>Verifying the Microsoft pairing and 2% fee against Pump.fun…</Notice>}<Notice>Pawns will publish repository-linked metadata and simulate the actual {mainCoin ? 'SOL-paired main coin' : 'Microsoft-paired'} launch. Review the exact recipient and costs before signing.</Notice><label className="agree"><input type="checkbox" checked={agreed} onChange={e => setAgreed(e.target.checked)}/><span>I’ve read the <a href="/terms" target="_blank" rel="noreferrer">Terms</a> and <a href="/risk" target="_blank" rel="noreferrer">risks</a>, and I won’t use this coin to impersonate the project or mislead buyers.</span></label><button className="button dark full" disabled={!!app.pending || (!policy && !mainCoin) || !agreed} onClick={() => void prepare()}>LAUNCH<ArrowUpRight size={17}/></button></>}
      </fieldset>
      {plan && <><Review plan={plan} busy={busy} now={now} owner={app.wallet.account?.address} error={error} feeApproval={!!approval.current} confirm={() => void confirm()}/><button disabled={!!busy} className="button secondary" onClick={() => { setPlan(null); mint.current = null; approval.current = null }}>Close review</button></>}
      {step > 0 && !plan && <div className="form-actions"><button disabled={!!busy || !!app.pending} onClick={() => setStep(step - 1)} className="button text-button"><ArrowLeft size={14}/>Back</button>{step < 4 && <button disabled={!!busy || !!app.pending} onClick={advance} className="button dark">Continue<ArrowRight size={14}/></button>}</div>}
      </>}
    </div></div><aside>{repo ? <RepoPreview repo={repo} contributors={development?.contributorCount} maintainer={maintainer}/> : <div className="repo-preview placeholder-preview"><div className="eyebrow">YOUR PROJECT / PREVIEW</div><div className="preview-repo-symbol"><Github size={38}/></div><h3>Built in public.<br/>Backed by anyone.</h3><p>The repository’s identity and stats appear here, with whether you maintain it.</p><div className="mini-code"><span><i>01</i> Connect GitHub</span><span><i>02</i> Choose any public repository</span><span><i>03</i> Make it a Commit</span></div></div>}<div className="launch-context"><div className="eyebrow">LAUNCH CONTEXT</div><dl><div><dt>GitHub</dt><dd>{app.user ? app.user.login : 'Not connected'}</dd></div><div><dt>Wallet</dt><dd>{app.wallet.account ? `${app.wallet.account.address.slice(0, 4)}…${app.wallet.account.address.slice(-4)}` : 'Not connected'}</dd></div><div><dt>Network</dt><dd><span className="status-dot"/>Solana mainnet</dd></div><div><dt>Launch engine</dt><dd>Pawns → Pump.fun</dd></div></dl></div><div className="create-note"><ShieldCheck size={17}/><p>Your wallet signs every transaction. The repository is checked with GitHub before launch, and maintainers are verified again whenever they claim.</p></div></aside></div></section>
}
