import { useEffect, useState } from 'react'
import { ArrowUpRight, Github, Plus, ShieldCheck } from 'lucide-react'
import { categories, type Allocation, type Category, type Eligibility, type Project, type Repository } from '../lib/types'
import { useApp } from './context'
import { request, errorText } from './api'
import { Empty, External, Link, Notice, number } from './components'
import { DevelopmentPanel, MarketStats, useDevelopment, useMarket, useProject } from './Project'
import { MarketChart, usdHistory, freshReference } from '../packages/pump-core/client'
import { MetricCharts } from './MetricCharts'
import { ProjectTreasury } from './Treasury'
export function DashboardIndex() {
  const { user, sessionLoaded } = useApp(), [items, setItems] = useState<Project[]>([]), [error, setError] = useState(''), [loading, setLoading] = useState(true)
  useEffect(() => { if (!user) { setLoading(!sessionLoaded); return } setLoading(true); let alive = true; void (async () => { const projects = await request<{ items: Project[] }>('/api/commit/projects'); const ids = new Set<number>(); let page: number | null = 1; while (page) { const response: { items: Repository[]; next: number | null } = await request(`/api/commit/repositories?page=${page}&for=claims`); response.items.forEach(repo => ids.add(repo.id)); page = response.next } if (alive) setItems(projects.items.filter(project => ids.has(project.repo.id))) })().catch(e => { if (alive) setError(errorText(e)) }).finally(() => { if (alive) setLoading(false) }); return () => { alive = false } }, [user?.id, sessionLoaded])
  return <section className="container dashboard-index"><div className="page-heading"><div className="eyebrow">YOUR WORKSPACE</div><h1>Keep <span className="serif">building.</span></h1><p>Your repositories, treasuries, and the people behind them.</p></div>{error && <p className="error" role="alert">{error}</p>}{loading && !user ? <Empty title="Loading">Checking your session…</Empty> : !user ? <Empty title="Your maintainer workspace"><a href={`/api/auth/login?next=${encodeURIComponent(location.pathname)}`} className="button dark"><Github size={16}/>Sign in with GitHub</a></Empty> : loading ? <Empty title="Verifying access">Checking your repository permissions…</Empty> : items.length ? <div className="dashboard-projects">{items.map(p => <Link to={`/dashboard/${p.repo.owner}/${p.repo.name}`} key={p.repo.id}><img src={p.repo.avatar} alt=""/><div><strong>{p.repo.owner} / {p.repo.name}</strong><span className="mono small">${p.coin.symbol} · {p.category}</span></div><ArrowUpRight size={18}/></Link>)}</div> : <Empty title="Your next chapter starts with a repository."><Link to="/create" className="button dark"><Plus size={16}/>Launch a repository</Link></Empty>}</section>
}
export function Dashboard({ owner, name }: { owner: string; name: string }) {
  const { project, error: projectError } = useProject(owner, name), app = useApp(), [authorized, setAuthorized] = useState(false), [error, setError] = useState(''), [notice, setNotice] = useState(''), [tab, setTab] = useState('Overview')
  const [eligibility, setEligibility] = useState<Eligibility[]>([]), [category, setCategory] = useState<Category>('Open Source'), [allocations, setAllocations] = useState<Allocation>({ treasury: 10000, maintainers: 0, contributors: 0, platform: 0 }), [busy, setBusy] = useState(false)
  const [login, setLogin] = useState(''), [reason, setReason] = useState(''), [evidence, setEvidence] = useState(''), [approved, setApproved] = useState(true)
  const [window, setWindow] = useState('1d'), [metric, setMetric] = useState<'fdv' | 'price'>('fdv')
  const market = useMarket(authorized ? project : null, window), development = useDevelopment(authorized ? project : null)
  async function refresh() { if (!project) return; const data = await request<{ project: Project; eligibility: Eligibility[] }>(`/api/commit/project/${project.repo.id}/dashboard`); setAuthorized(true); setEligibility(data.eligibility); setCategory(data.project.category); setAllocations(data.project.allocations) }
  useEffect(() => { setAuthorized(false); if (project && app.user) void refresh().catch(e => setError(errorText(e))) }, [project?.repo.id, app.user?.id])
  async function saveSettings() { if (!project) return; setBusy(true); setError(''); try { await request('/api/commit/settings', { repositoryId: project.repo.id, category, allocations }); setNotice('Allocation targets saved. Payouts still require a claim request and manual settlement by Commit.'); await refresh() } catch (e) { setError(errorText(e)) } finally { setBusy(false) } }
  async function saveContributor() { if (!project) return; setBusy(true); setError(''); try { await request('/api/commit/contributors/approve', { repositoryId: project.repo.id, login, approved, reason, evidence: evidence.split('\n').map(v => v.trim()).filter(Boolean) }); setNotice('Contributor eligibility saved with an audit record.'); await refresh(); setLogin(''); setReason(''); setEvidence('') } catch (e) { setError(errorText(e)) } finally { setBusy(false) } }
  if (!project || !authorized) return <section className="container page-heading"><div className="eyebrow">PROJECT WORKSPACE</div><h1>{owner} / {name}</h1>{(projectError || error) && <p className="error" role="alert">{projectError || error}</p>}{app.user ? <p>Maintainer access is verified server-side for every dashboard request and settings change.</p> : <a href={`/api/auth/login?next=${encodeURIComponent(location.pathname)}`} className="button dark">Sign in with GitHub</a>}</section>
  const usd = !!freshReference(market.data?.market.usdReference)
  return <section className="container dashboard-page"><div className="dashboard-heading"><div><div className="eyebrow">MAINTAINER WORKSPACE</div><h1>{owner} <span>/</span> {name}</h1></div><Link to={`/${owner}/${name}`} className="button secondary">Public project page<ArrowUpRight size={15}/></Link></div><div className="dashboard-layout"><nav aria-label="Dashboard sections">{['Overview', 'Market', 'Treasury', 'Contributors', 'Repository', 'Revenue', 'Settings'].map(item => <button key={item} className={tab === item ? 'active' : ''} aria-current={tab === item ? 'page' : undefined} onClick={() => { setTab(item); setNotice('') }}>{item}<span>↗</span></button>)}<div className="dashboard-permission"><ShieldCheck size={20}/><p>Repository permissions<br/>verified server-side.</p></div></nav><div className="dashboard-content">{error && <p className="error" role="alert">{error}</p>}{notice && <Notice>{notice}</Notice>}
    {['Overview', 'Market', 'Revenue'].includes(tab) && <><div className="eyebrow">{tab.toUpperCase()} / LIVE PROJECT DATA</div><h2>{tab === 'Overview' ? 'The project at a glance.' : tab === 'Market' ? 'Market activity.' : 'Revenue for what comes next.'}</h2><MarketStats data={market.data} extra={market.extra} quote={project.coin.quote}/>{market.error && <p className="error" role="alert">{market.error}</p>}{tab !== 'Revenue' && <MarketChart points={usd ? usdHistory(market.data?.history || []) : market.data?.history || []} symbol={usd ? 'USD' : market.data?.market.quote.symbol || project.coin.quote?.symbol || 'MSFTx'} metric={metric} setMetric={setMetric} window={window} setWindow={setWindow} updated={market.data?.market.updatedAt}/>}{tab === 'Overview' && <div className="dashboard-summary"><div><span className="eyebrow">GITHUB STARS</span><strong>{number(project.repo.stars)}</strong></div><div><span className="eyebrow">CONTRIBUTORS</span><strong>{number(development.data?.contributorCount)}</strong></div><div><span className="eyebrow">APPROVED BUILDERS</span><strong>{eligibility.filter(e => e.approved).length}</strong></div></div>}{tab === 'Revenue' && <><Notice>Lifetime fees are indexed separately for this coin from finalized Pump.fun and canonical PumpSwap events. Protocol collection does not reset earned totals. Payouts are recorded separately after a verified manual transfer. {market.data?.creatorFees?.notice}</Notice><button className="button primary" onClick={() => setTab('Treasury')}>View treasury / request claim</button><div className="allocation-display">{Object.entries(allocations).map(([key, value]) => <div key={key}><span>{key}</span><strong>{value / 100}%</strong><progress value={value} max={10000}/></div>)}</div><p className="muted">Allocation targets guide manual review; they do not automatically grant or send payouts. The operator approves each request before settlement.</p><button className="button secondary" onClick={() => setTab('Settings')}>Edit funding policy</button></>}</>}
    {['Overview', 'Market', 'Revenue'].includes(tab) && <MetricCharts points={market.extra?.history || []} quoteSymbol={project.coin.quote?.symbol || 'MSFTx'}/>}
    {tab === 'Overview' && <DevelopmentPanel data={development.data} error={development.error}/>}
    {tab === 'Treasury' && <ProjectTreasury repositoryId={project.repo.id}/>}
    {tab === 'Contributors' && <><div className="eyebrow">HUMAN-APPROVED ELIGIBILITY</div><h2>Fund meaningful contributions.</h2><p className="muted">Consider merged PRs, reviews, accepted work, issue resolution, and maintainer responsibility. A raw commit count is never enough.</p><div className="table-scroll"><table><thead><tr><th>Contributor</th><th>Eligibility</th><th>Verified wallet</th><th>Rationale</th></tr></thead><tbody>{eligibility.map(item => <tr key={item.userId}><td><External href={`https://github.com/${item.login}`}>{item.login}</External></td><td>{item.approved ? 'Approved' : 'Not eligible'}</td><td className="break">{item.wallet || 'Not linked'}</td><td>{item.reason}{item.evidence.map(url => <External key={url} href={url}>Evidence</External>)}</td></tr>)}</tbody></table>{!eligibility.length && <p className="table-empty">No eligibility decisions yet.</p>}</div><div className="form-panel"><h3>Record an eligibility decision</h3><fieldset disabled={busy}><label>GitHub username<input value={login} onChange={e => setLogin(e.target.value)} placeholder="contributor"/></label><label>Decision<select value={String(approved)} onChange={e => setApproved(e.target.value === 'true')}><option value="true">Approve eligibility</option><option value="false">Revoke / decline eligibility</option></select></label><label>Contribution rationale<textarea rows={3} value={reason} onChange={e => setReason(e.target.value)} placeholder="Describe accepted work, reviews, issue resolution, or maintainer responsibilities."/></label><label>PR / issue evidence from this repository<textarea rows={3} value={evidence} onChange={e => setEvidence(e.target.value)} placeholder={`${project.repo.url}/pull/123\nOne URL per line`}/></label><button className="button dark" onClick={() => void saveContributor()}>{busy ? 'Saving…' : 'Save eligibility decision'}</button></fieldset></div><p className="small muted">Contributors link their own wallet in <Link to="/account">Account settings</Link>. Admins cannot assign someone else’s wallet.</p></>}
    {tab === 'Repository' && <DevelopmentPanel data={development.data} error={development.error}/>}
    {tab === 'Settings' && <><div className="eyebrow">PROJECT SETTINGS</div><h2>Define how the project gives back.</h2><div className="form-panel"><fieldset disabled={busy}><label>Category<select value={category} onChange={e => setCategory(e.target.value as Category)}>{categories.map(item => <option key={item}>{item}</option>)}</select></label><h3>Allocation policy · basis points</h3><p className="small muted">100 basis points = 1%. Total must be 10,000. This policy records targets, not automatic payouts.</p>{(Object.keys(allocations) as (keyof Allocation)[]).map(key => <label className="allocation-input" key={key}><span>{key}</span><input aria-label={`${key} allocation basis points`} type="number" min={0} max={10000} step={1} value={allocations[key]} onChange={e => setAllocations({ ...allocations, [key]: Number(e.target.value) })}/></label>)}<p className="mono small">TOTAL: {Object.values(allocations).reduce((a, b) => a + b, 0)} / 10,000</p><button className="button dark" onClick={() => void saveSettings()}>{busy ? 'Saving…' : 'Save project settings'}</button></fieldset></div><h3>Immutable launch settings</h3><dl className="review-summary"><div><dt>Mint</dt><dd className="break mono">{project.coin.mint}</dd></div><div><dt>Creator wallet</dt><dd className="break mono">{project.coin.owner}</dd></div><div><dt>Launch date</dt><dd>{new Date(project.coin.createdAt).toLocaleString()}</dd></div><div><dt>Repository ID</dt><dd>{project.repo.id}</dd></div></dl></>}
  </div></div></section>
}
