import { useEffect, useState } from 'react'
import { ArrowUpRight, Check, Copy, GitFork, GitPullRequest, Github, Star, Tag, Users } from 'lucide-react'
import { api, explorerUrl, formatUnits, freshReference, MarketChart, marketNumber, pumpUrl, short, TradePanel, usdHistory, usdNumber, usdValue, type MarketResponse, type QuoteAsset } from '../packages/pump-core/client'
import { MICROSOFT_ASSET } from '../lib/pump/policy'
import { ProjectTreasury } from './Treasury'
import type { Development, Project } from '../lib/types'
import type { ExtraMarket } from '../lib/indexer/market'
import { useApp } from './context'
import { ClaimBadge, Empty, External, ForkLabel, LaunchBadge, Link, Notice, number } from './components'
import { errorText, request } from './api'

export function useProject(owner: string, name: string) {
  const [project, setProject] = useState<Project | null>(null), [error, setError] = useState('')
  useEffect(() => { let alive = true; void request<{ project: Project }>(`/api/commit/projects/${encodeURIComponent(owner)}/${encodeURIComponent(name)}`).then(value => { if (alive) setProject(value.project) }).catch(e => { if (alive) setError(errorText(e)) }); return () => { alive = false } }, [owner, name])
  return { project, error }
}
export function useDevelopment(project: Project | null) {
  const [data, setData] = useState<Development | null>(null), [error, setError] = useState('')
  useEffect(() => { if (!project) return; let alive = true; void request<Development>(`/api/commit/project/${project.repo.id}/development`).then(value => { if (alive) setData(value) }).catch(e => { if (alive) setError(errorText(e)) }); return () => { alive = false } }, [project?.repo.id])
  return { data, error }
}
export function useMarket(project: Project | null, window = '1h') {
  const app = useApp(), [data, setData] = useState<MarketResponse | null>(null), [error, setError] = useState(''), [extra, setExtra] = useState<ExtraMarket | null>(null)
  useEffect(() => {
    if (!project) return; let alive = true, running = false
    const refresh = async () => { if (running) return; running = true; try { const query = new URLSearchParams({ window }); if (app.wallet.account) query.set('owner', app.wallet.account.address); const result = await api<MarketResponse>(`market/${project.coin.mint}?${query}`); if (alive) { setData(result); setError('') } } catch (e) { if (alive) setError(errorText(e)) } finally { running = false } }
    void refresh(); const timer = setInterval(() => { if (!document.hidden) void refresh() }, 10000); return () => { alive = false; clearInterval(timer) }
  }, [project?.coin.mint, app.wallet.account?.address, window, app.activity?.status])
  useEffect(() => { if (!project) return; let alive = true; const load = () => void request<ExtraMarket>(`/api/commit/project/${project.repo.id}/market`).then(value => { if (alive) setExtra(value) }).catch(() => {}); load(); const timer = setInterval(load, 60000); return () => { alive = false; clearInterval(timer) } }, [project?.repo.id])
  return { data, error, extra }
}
export function DevelopmentPanel({ data, error }: { data: Development | null; error: string }) {
  const days = Array.from({ length: 84 }, (_, index) => { const date = new Date(); date.setUTCDate(date.getUTCDate() - 83 + index); const key = date.toISOString().slice(0, 10); return { date: key, count: data?.events.filter(event => event.created_at.startsWith(key)).length || 0 } })
  return <section className="development-section" id="development"><div className="section-heading"><div><div className="eyebrow">DEVELOPMENT / FROM GITHUB</div><h2>Proof of work.</h2></div><span className="mono small muted">{data ? `UPDATED ${new Date(data.fetchedAt).toLocaleDateString()}` : 'FETCHING GITHUB'}</span></div>{error && <p className="error" role="alert">{error}</p>}<div className="development-grid"><div className="activity-panel"><h3>Repository activity</h3><div className="contribution-grid">{days.map(day => <span key={day.date} title={`${day.date}: ${day.count} recent events`} data-level={Math.min(3, day.count)}/>)}</div><div className="contribution-legend"><span>Recent public events</span><span>Less<i/><i/><i/><i/>More</span></div><p className="small muted">GitHub returns at most 100 recent events; empty cells are not proof of inactivity. Activity is never an automatic reward score.</p><div className="contributors-avatars">{data?.contributors.slice(0, 18).map(c => <a key={c.id} href={c.html_url} title={c.login} target="_blank" rel="noreferrer"><img src={c.avatar_url} alt={c.login}/></a>)}</div><p className="mono small">{data ? `${number(data.contributorCount)} contributors` : 'Contributors loading…'}</p></div><div className="development-lists"><h3><GitPullRequest size={17}/>Recent merged pull requests</h3>{data?.pulls.length ? data.pulls.slice(0, 5).map(p => <a className="activity-row" key={p.number} href={p.html_url} target="_blank" rel="noreferrer"><span className="mono muted">#{p.number}</span><span>{p.title}<small>{p.user.login} · {new Date(p.merged_at).toLocaleDateString()}</small></span><ArrowUpRight size={14}/></a>) : <p className="muted small">{data ? 'No merged pull requests in the recent closed-PR window.' : 'Loading merged pull requests…'}</p>}<h3><Tag size={17}/>Recent releases</h3>{data?.releases.length ? data.releases.slice(0, 3).map(r => <a key={r.tag_name} href={r.html_url} className="activity-row" target="_blank" rel="noreferrer"><span className="mono">{r.tag_name}</span><span>{r.name}<small>{new Date(r.published_at).toLocaleDateString()}</small></span><ArrowUpRight size={14}/></a>) : <p className="muted small">{data ? 'No published releases yet.' : 'Loading releases…'}</p>}</div></div></section>
}
const SUBSCRIPT = '₀₁₂₃₄₅₆₇₈₉'
/** Very small prices in compact notation, e.g. 0.0000040244 → "0.0₅4024", so they fit one line. Null when not tiny. */
export function tinyPrice(value: number | null | undefined, prefix: string, suffix: string) {
  if (value == null || !Number.isFinite(value) || value <= 0 || value >= 0.001) return null
  const [mantissa, exponent] = value.toExponential(3).split('e'), zeros = -Number(exponent) - 1   // 4.024e-6 → 5 zeros
  const digits = mantissa.replace('.', '').replace(/0+$/, '') || '0'
  return `${prefix}0.0${String(zeros).split('').map(d => SUBSCRIPT[Number(d)]).join('')}${digits}${suffix}`
}
export function MarketStats({ data, extra, quote }: { data: MarketResponse | null; extra: ExtraMarket | null; quote?: QuoteAsset }) {
  const market = data?.market, usd = !!freshReference(market?.usdReference), fees = data?.creatorFees?.amount, asset = market?.quote || quote || MICROSOFT_ASSET
  return <div className="market-stats">{[['Price', usd ? tinyPrice(usdValue(market?.price, market?.usdReference), '$', '') ?? usdNumber(usdValue(market?.price, market?.usdReference)) : tinyPrice(market?.price, '', ` ${asset.symbol}`) ?? `${marketNumber(market?.price)} ${asset.symbol}`], ['Market cap', usd ? usdNumber(usdValue(market?.fdv, market?.usdReference)) : `${marketNumber(market?.fdv)} ${asset.symbol}`], ['24H volume · USD', usdNumber(extra?.volume24h)], ['Holders', number(extra?.holders)], ['Creator revenue', fees == null ? data?.creatorFees?.status === 'unavailable' ? 'Unavailable' : 'Indexing…' : `${formatUnits(fees, asset.decimals)} ${asset.symbol}`]].map(([label, value]) => <div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>
}
export function ProjectPage({ owner, name }: { owner: string; name: string }) {
  const { project, error } = useProject(owner, name), app = useApp(), development = useDevelopment(project)
  const [window, setWindow] = useState('1h'), [metric, setMetric] = useState<'fdv' | 'price'>('fdv'), [copied, setCopied] = useState(false), [badgeCopied, setBadgeCopied] = useState(false), market = useMarket(project, window)
  if (!project) return <section className="container page-heading"><Empty title={error ? 'Repository unavailable' : 'Reading repository…'}>{error || 'Loading the repository and its finalized token.'}</Empty></section>
  const { coin } = project, community = project.launch === 'community', slug = `${project.repo.owner}/${project.repo.name}`, repo = development.data?.repository || project.repo, data = market.data, usd = !!freshReference(data?.market.usdReference), quote = data?.market.quote || coin.quote || MICROSOFT_ASSET
  return <section className="container project-page">
    <div className="project-breadcrumb"><Link to="/explore">markets</Link><span>/</span><span>{repo.owner} / {repo.name}</span><Link to={`/dashboard/${repo.owner}/${repo.name}`} className="project-manage">dashboard<ArrowUpRight size={12}/></Link></div>
    <div className="project-terminal" id="trading"><div className="terminal-main">
      <header className="project-header"><div className="eyebrow">{project.category.toLowerCase()} / {quote.symbol} / {data?.market.route === 'pool' ? 'pumpswap' : data?.market.route === 'migrating' ? 'graduating' : 'pump.fun'}</div><div className="instrument-heading"><h1 aria-label={`${repo.owner} / ${repo.name}`}><span className="terminal-symbol">{coin.symbol}</span><span className="terminal-repo-name">{repo.owner} / <b>{repo.name}</b></span></h1><img className="project-logo" src={coin.image || repo.avatar} alt=""/></div><div className="instrument-subline"><LaunchBadge project={project}/><ClaimBadge project={project}/><ForkLabel repo={repo}/><External href={repo.url}><Github size={12}/>github</External><External href={pumpUrl(coin.mint)}>pump.fun</External></div>{repo.description && <p>{repo.description}</p>}{project.hidden && <Notice><b>Delisted from Commit</b> ({project.hidden.reason}). The token still exists on Solana and may trade elsewhere; trading through Commit is off. Its creator fees remain claimable by the repository’s maintainers.</Notice>}{community && <Notice><b>Community launch</b> by @{project.launchedBy || 'a Commit user'}. It was not created or endorsed by the maintainers of {slug}. Its creator fees are reserved for them: maintainers of {slug}, and contributors they approve, can sign in with GitHub and <a href="#treasury">claim them here</a>. {project.claimedAt ? `A maintainer (@${project.claimedBy}) has claimed it; that is not an endorsement.` : 'No maintainer has claimed it yet.'}</Notice>}{repo.forked && <Notice>This repository is a fork{repo.parent ? ` of ${repo.parent.owner}/${repo.parent.name}` : ''}. Its maintainers, not the original project’s, claim this coin’s fees.</Notice>}</header>
      <MarketStats data={data} extra={market.extra} quote={quote}/>
      {market.error && <p className="error" role="alert">{market.error}</p>}
      <MarketChart points={usd ? usdHistory(data?.history || []) : data?.history || []} symbol={usd ? 'USD' : quote.symbol} metric={metric} setMetric={setMetric} window={window} setWindow={setWindow} updated={data?.market.updatedAt}/>
      <section className="curve-panel"><div><strong>bonding curve</strong><span className="mono">{data ? `${number(data.market.progress)}%` : '—'}</span></div><progress max={100} value={data?.market.progress || 0}/><p>{data?.market.route === 'pool' ? 'Graduated. Trading routes to the canonical PumpSwap pool.' : data?.market.route === 'migrating' ? 'Curve complete. Awaiting PumpSwap migration.' : 'Pump.fun bonding curve → PumpSwap at graduation.'}</p></section>
      <div className="github-statline"><span><Star size={13}/><strong>{number(repo.stars)}</strong>stars</span><span><GitFork size={13}/><strong>{number(repo.forks)}</strong>forks</span><span><Users size={13}/><strong>{number(development.data?.contributorCount)}</strong>builders</span><span><i className="language-dot"/>{repo.language || 'Open source'}</span><span><Tag size={13}/>{development.data?.releases[0]?.tag_name || 'no release indexed'}</span></div>
      <p className="data-note">Creator revenue: lifetime finalized fees, including claims. {data?.creatorFees?.notice} Volume and holders use external indexes; — means unavailable.</p>
    </div><div className="terminal-order"><div className="order-heading"><span>spot / {quote.symbol}</span><span>solana mainnet</span></div>{project.hidden ? <Notice>Trading through Commit is off for this delisted coin.</Notice> : <TradePanel coin={coin} data={data} wallet={app.wallet} connect={app.connect} pending={!!app.pending} activity={app.activity} onPending={app.onPending} onActivity={app.onActivity}/>}<p className="data-note risk-note">Speculative. Not investment advice. {community ? 'Not endorsed by the repository’s maintainers. ' : ''}<Link to="/risk">Read the risks</Link>.</p><div className="order-context"><div className="eyebrow">project funding</div><dl><div><dt>creator fee</dt><dd>{coin.creatorTaxBps ? `${coin.creatorTaxBps / 100}%` : 'Pump.fun schedule'}</dd></div><div><dt>mint</dt><dd><External href={`https://solscan.io/token/${coin.mint}`}>{short(coin.mint)}</External></dd></div><div><dt>paired asset</dt><dd>{quote.name}</dd></div></dl><p>{project.fundingMode === 'manual-v1' ? `This coin has its own treasury ledger. Maintainers of ${slug}, and contributors they approve, request payouts; Commit sends the fees manually.` : 'Creator fees accrue to the launch treasury.'}</p><a href="#treasury" className="button secondary full">View treasury / request claim</a></div></div></div>
    <nav className="project-sections" aria-label="Project sections"><a href="#trades">recent trades<span>{data?.trades.length ?? '—'}</span></a><a href="#development">development</a><a href="#treasury">treasury</a><a href="#trading">market ↑</a></nav>
    <section className="trades-section" id="trades"><div className="section-heading"><h3>Recent trades</h3><span className="eyebrow">finalized commit orders</span></div><div className="table-scroll"><table><thead><tr><th>side</th><th>pay / sell limit</th><th>minimum receive</th><th>wallet</th><th>time</th><th>transaction</th></tr></thead><tbody>{data?.trades.map(trade => <tr key={trade.signature}><td className={trade.side === 'buy' ? 'positive' : 'negative'}>{trade.side}</td><td>{formatUnits(trade.amountIn, trade.side === 'buy' ? data.market.quote.decimals : data.market.tokenDecimals)} {trade.side === 'buy' ? data.market.quote.symbol : coin.symbol}</td><td>{formatUnits(trade.minimumOutput, trade.side === 'buy' ? data.market.tokenDecimals : data.market.quote.decimals)} {trade.side === 'buy' ? coin.symbol : data.market.quote.symbol}</td><td>{short(trade.owner)}</td><td>{new Date(trade.time).toLocaleString()}</td><td><External href={explorerUrl(trade.signature)}>view</External></td></tr>)}</tbody></table>{!data?.trades.length && <p className="table-empty">Finalized trades placed through Commit will appear here.</p>}</div><p className="data-note">Order limits shown, not exact fills. Trades from other interfaces are not included.</p></section>
    <section id="treasury"><ProjectTreasury repositoryId={repo.id}/></section><DevelopmentPanel data={development.data} error={development.error}/><section className="project-details"><div>{!project.hidden && <><span className="eyebrow">README BADGE</span><img className="readme-badge" src={`/badge/${project.repo.owner}/${project.repo.name}.svg`} alt={`Backed on Commit: $${coin.symbol}`}/><button className="copy-address" aria-label="Copy README badge markdown" onClick={() => void navigator.clipboard.writeText(`[![Backed on Commit](${location.origin}/badge/${project.repo.owner}/${project.repo.name}.svg)](${location.origin}/${project.repo.owner}/${project.repo.name})`).then(() => setBadgeCopied(true)).catch(() => setBadgeCopied(false))}><code>{`[![Backed on Commit](${location.origin}/badge/${project.repo.owner}/${project.repo.name}.svg)](${location.origin}/${project.repo.owner}/${project.repo.name})`}</code>{badgeCopied ? <Check size={15}/> : <Copy size={15}/>}</button><p>Maintainers: add this to your README so supporters find the coin.</p></>}<span className="eyebrow">PAIRED-ASSET MINT · {quote.symbol}</span><code>{quote.mint}</code></div><div><span className="eyebrow">PUMP.FUN MINT</span><button className="copy-address" onClick={() => void navigator.clipboard.writeText(coin.mint).then(() => setCopied(true)).catch(() => setCopied(false))}><code>{coin.mint}</code>{copied ? <Check size={15}/> : <Copy size={15}/>}</button><External href={explorerUrl(coin.signature)}>Launch transaction · {new Date(coin.createdAt).toLocaleDateString()}</External><p className="small"><Link to={`/report?coin=${encodeURIComponent(slug)}`} className="text-link">report this coin</Link></p><p className="small muted">{community ? `Community launch by @${project.launchedBy || 'a Commit user'}; the repository was checked as public ${new Date(project.repo.verifiedAt).toLocaleString()}. Not a GitHub or maintainer endorsement.` : `Maintainer permission verified ${new Date(project.repo.verifiedAt).toLocaleString()}. Verification records launch authorization, not a GitHub endorsement.`}</p></div></section>
  </section>
}
